# File managed by pluginsync
pluginsync_config: '0.1.12'
managed_files:
- .github
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- .pluginsync.yml
- .travis.yml
- CONTRIBUTING.md
- LICENSE
- Makefile
- scripts
- scripts/build.sh
- scripts/common.sh
- scripts/deps.sh
- scripts/large.sh
- scripts/pre_deploy.sh
- scripts/test
- scripts/test/large_spec.rb
- scripts/test/spec_helper.rb
- scripts/test.sh
