#http://www.apache.org/licenses/LICENSE-2.0.txt
#
#
#Copyright 2015 Intel Coporation
#
#Licensed under the Apache License, Version 2.0 (the "License");
#you may not use this file except in compliance with the License.
#You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
#Unless required by applicable law or agreed to in writing, software
#distributed under the License is distributed on an "AS IS" BASIS,
#WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#See the License for the specific language governing permissions and
#limitations under the License.

reporting-disabled = true

[meta]
  dir = "/var/opt/influxdb/meta"

[initialization]
  join-urls = ""

[authentication]
  enabled = false

[admin]
  enabled = true
  port = 8083
  assets = "/opt/influxdb/current/admin"

[api]
  bind-address = "0.0.0.0"
  port = 8086

[collectd]
  enabled = false

[opentsdb]
  enabled = false

[[udp]]
  enabled = false

[broker]
  dir = "/data/broker"
  enabled = true
  election-timeout = "0"

[data]
  dir = "/data/db"
  enabled = true
  retention-auto-create = true
  retention-check-enabled = true
  retention-check-period = "10m0s"
  retention-create-period = "45m0s"
  max-wal-size = 104857600
  wal-flush-interval = "10m"
  wal-partition-flush-delay = "2s"
  wal-dir = "/data/wal"
  wal-enable-logging = true

[http]
  enabled = true
  bind-address = "0.0.0.0:8086"
  auth-enabled = false
  log-enabled = true
  write-tracing = false
  pprof-enabled = false
  https-enabled = false

[snapshot]
  enabled = false

[logging]
  write-tracing = false
  raft-tracing = false
  level  = "info"
  file   = "/opt/influxdb/shared/log.txt"

[monitoring]
  enabled = false

[debugging]
  pprof-enabled = false

[continuous_queries]
  recompute-previous-n = 2
  recompute-no-older-than = "10m0s"
  compute-runs-per-interval = 10
  compute-no-more-than = "2m0s"
  disabled = false

[hinted-handoff]
  enabled = true
  dir = "/var/opt/influxdb/hh"
